### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pea3nut** [pea3nut/timeline#1]
## 马上要做

- [ ] 官网编辑器优化：增加行号、保存按钮改为文字且常驻、报错有更友好的提示并提供建议、报错后禁用扩展继续绘制、解决冲突尝试次数太多给予警告
- [ ] Rules 绘制中国编年史时，删掉“楚汉相争（西楚）”里面的 description 会导致直接无法解决冲突
- [x] 为所有 css 类添加 sn- 前缀
- [ ] 调整包依赖，逻辑上只用 dist 其实应该 0 依赖，毕竟都打包好了
- [ ] 报 too many loops 的时候，打印出所有冲突
- [x] 需要对外暴露 Ext 和更多东西，对于 Rules 和 Polar-day 都是
- [ ] theme 的定义实在是太傻了，甚至外部调用 `Rules.Timeline.mount` 都要手动传入 theme，太傻了
- [x] 初始轴500的高度太高，在做极小 demo 的时候非常不方便
- [ ] 下边的数据会导致轴体显示不正常，MileStone 明显不对
```js
[{
    date: '2010-3-9',
    endDate: '2014-3-9',
    title: 'Event 1',
}, {
    date: '2011-8-31',
    title: 'Event 2',
}, {
    date: '2012-12-27',
    title: 'Event 3',
}]
```
- [ ] ConflictFixer 和 BoxGenerator 会冲突，导致 box 生成的不准
- [x] ~~EventBody 的 title 中包含 html 会导致 label 看上去很奇怪~~ 实际上是 BoxGenerator 生成的元素有 title 属性而已
- [x] Rules：浮动后的 EventMark 很奇怪，更靠内侧了
- [ ] 导出的思路似乎不对，导出按理说应该不必引用全量的 Short-Night才对
- [x] 更智能的扩大时间轴来解决冲突，可以折半查找？或者查找超过一定次数时给予警告
- [x] Rules 中日期的排版有问题
  - [x] 忘加空格了
  - [x] 一旦事件浮动，范围性的日期将折行
- [x] 解决冲突时优先 float 没有 description 的 Event
- [ ] 部署到 pea3nut.info
- [x] 提供一个统一的入口函数，不像非 Timeline 作者暴露太多
- [ ] 更新文档
  - [ ] 在官网增加 Rules 和 Polar-day 的使用文档
  - [ ] Wiki 更新开发 Timeline 的文档
  - [ ] README.md 增加开发 Short-Night 的文档
- [x] 使用 moveto 1.8.x
- [x] 为Rules增加Debug标语
- [x] 测试 Rules 的外部引用
- [x] 移除文档中定义`process`的依赖
- [x] 2x 屏兼容
- [x] 生成纯图片，包括文字
- [x] 做一个网站来 demo
  - [x] Git Pages
  - [ ] 酷炫化

## 必须在招募小伙伴前完成

- [x] 将编译改为 js + d.ts 的方式
- [x] 重新组织结构，将大块剥离成小块
- [x] 自动播放 walk on 动画支持
- [x] 剥离出 colors 主题
- [x] milestone 对齐到合适的时间
  现在的 milestone 是基于算式整除对齐的，但是每个月的日期不一样，没办法精准的对齐到某个季度的第一天。因此需要基于 Date 计算。scale 好像不需要。
- [x] ~~BreakpointAnimation 支持使用数组和 alias 设置断点~~ 感觉没啥必要，反而增加逻辑复杂性
- [x] ~~Themes文件build出来不包含engine代码~~ 貌似很难实现，想要Theme不和Engine一起打包且正常使用Engine代码，必须挂到全局。Engine代码也没多少
- [x] es&ts-lint
- [x] CI
- [x] 更新注释及README.md
- [x] ~~利用 colors 的不确定性画一个会动的动态时间线~~ 并不好看
- [x] 2种动画机制
  - [x] draw 时动画walk-on
  - [x] drawFrom 时动画渐进画
- [x] DrawInfo 的导入导出， 可以直接通过相同的DrawInfo画出相同的图
- [x] ~~将 ExtensionMenager 改一个骚气的名字~~算了算了，引擎名字和主题名字已经很骚气了，而且debug模式下还有台词。。。算了算了
- [x] 增加自动生成的文档
- [x] 制作 ts + webpack 的教程

## 在正式发布前必须要完成

- [ ] 支持制作一次线上事故，Short Night 拥有按小时和分钟分割
- [x] 绘制中国编年史。调整里程碑和scale的计算逻辑
- [ ] 支持配置动画时间和容器
- [x] 一个 Event 支持 now 关键字
- [ ] 支持折叠一个 Event
- [ ] 可以通过折叠 Event 来修复 conflict
- [ ] 建立一个 awesome-short-night，把 EventColorPicker 放进去
- [ ] 制作 browser + js 的教程
- [ ] 可以自定义部分DrawInfo
- [ ] 检查 typedoc 生成的文档
- [ ] 为每个可重写的方法增加稳定性评级
- [ ] 兼容性测试。包含 Safari 
- [ ] 如何正确的计算逻辑组件的Box？叶子组件的Box可能被扩展动态修改。或许应该移除逻辑组件的box？
- [x] 更新分支
- [x] 分离 engine 和 theme 到完全不同的仓库
- [x] EventAxis 的文本对齐支持
- [x] 增加禁用扩展的支持。移除所有 Component 对扩展的强依赖，确保 Component 可以脱离扩展运行
- [x] 新Theme设计 #2
  - [x] 文档书写
  - [x] 提需求

## 不是特别着急

- [ ] 文档 i18n
- [ ] BreakpointAnimation 有些动画被播放多遍（当axis被拉长会重新出发 walk on）
- [ ] 解决冲突通过 apply Event 而不是其子节点
- [ ] 调整子节点 apply 其他兄弟节点，以更新子节点之间的依赖
- [ ] ~~动态计算 GRID~~
- [x] 更智能的评估一开始的 axisLength
- [ ] 为 extension 增加 log 支持
- [ ] 更聪明的计算 cast 来 fix conflict
  - [ ] EventAxis2EventAxis：目前只是基于长度，应该综合长度和与其他EventAxis conflict 程度
- [x] 防止忘记调用 `return super.xxx()`。可以考虑让Component的各个方法返回一个特殊的值来保证
- [ ] 使用 eslint 的 [parser](https://github.com/eslint/typescript-eslint-parser) 来 lint ts代码
- [ ] 调整冲突时，若可以同时移动2个 EventBody 且不影响其他 EventBody ，就可以允许移动2个
- [ ] 支持自定义的调整冲突 
- [ ] 可视化编辑器，不用用户输入JOSN
